# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
import unittest

class TestProverka():
  def setup_method(self):
    self.driver = webdriver.Chrome("C:\\chromedriver\\chromedriver.exe")
    self.vars = {}



  def test_proverka(self):
    self.driver.get("http://addressbook/")
    self.driver.set_window_size(820, 647)
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    self.driver.find_element(By.NAME, "pass").send_keys("secret")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    self.driver.find_element(By.LINK_TEXT, "Группы").click()
    self.driver.find_element(By.NAME, "new").click()
    self.driver.find_element(By.NAME, "group_name").click()
    self.driver.find_element(By.NAME, "group_name").send_keys("dfred")
    self.driver.find_element(By.NAME, "group_header").click()
    self.driver.find_element(By.NAME, "group_header").send_keys("rtyhgvbn")
    self.driver.find_element(By.NAME, "group_footer").click()
    self.driver.find_element(By.NAME, "group_footer").send_keys("cvfgtrrr")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "group page").click()
    self.driver.find_element(By.LINK_TEXT, "Выйти").click()

  def teardown_method(self):
    self.driver.quit()

if __name__ == '__main__':
  unittest.main()
